config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'profile/create/:id', to: 'profiles#new'
  get '/:id', to: 'posts#destroy'
  get 'commenters/create'
  get ':id/commenters', to: 'commenters#create'
  get 'users/show'
  get 'users/add_user'
  get 'profiles/add_user'
  get 'users/reject_user/:id', to: 'users#reject_user'
  get 'users/acceptuser'
  get 'users/friend'
  get 'users/profile'
  get ':controller/:action/:id'
  patch 'users/updateprofile/:id', to: 'users#updateprofile'
  put 'post/like/:id', to: 'posts#like'
  put 'post/unlike/:id', to: 'posts#unlike'
  get 'post/like/:id', to: 'posts#like'
  get 'post/unlike/:id', to: 'posts#unlike'
  get 'post/new', to: 'posts#new'
  get 'users/friend/:id', to: 'users#unfriend'



  devise_for :users

  resources :posts , :path => '/' do
     put 'like', to: 'posts#like'
     put "unlike", to: "posts#unlike"
    resources :commenters
  end
  resource :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, :dependent => :destroy
  has_attached_file :avatar,:default_url => ActionController::Base.helpers.asset_path('assetsmissing.png')
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :firstname, :lastname, presence: true
  validates_format_of :firstname, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  validates_format_of :lastname, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/


#def self.search(search)
#  where("firstname LIKE ? OR lastname LIKE ? ", "%#{search}%", "%#{search}%") 
 
#end

#def full_name
#{}"#{self.firstname} #{self.lastname}"
#end


#def self.search_by_full_name(search)
#	where("CONCAT_WS(' ', firstname, lastname) LIKE ?", "%#{search}%")
#end





def self.search_by_full_name(search)
 @names = search.split(" ")
 where("firstname LIKE ? AND lastname LIKE ?", "%#{@names[0]}","%#{@names[1]}" )
end

def self.lastname(search)
  where("lastname LIKE ? ", "%#{search}%") 
end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :set_profile, only: [:show, :edit, :update, :destroy,]
  before_action :set_user, only: [:adduser]
  load_and_authorize_resource :only => [:edit]


  def adduser

    current_user.friend_request(set_user)
    flash[:notice] = "You Added #{@user.profile.firstname}"
    redirect_to @user.profile
  end

  # GET /profiles
  # GET /profiles.json
  def index
   
    @profile = params[:search]
    authorize! :read, @profile
    if Profile.where(lastname: @profile).present?
       @profile = Profile.lastname(params[:search])
    else
    @profile = Profile.search_by_full_name(params[:search])

    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    
  end

  # GET /profiles/new
  def new
 
  end

  # GET /profiles/1/edit
  def edit
 
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
      if @profile.update(profile_params)
        redirect_to @profile
      else
        redirect_to @profile
      end
    end


  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :firstname, :lastname, :birthday, :about, :gender, :avatar)

    end
   
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :user_id, required: true, value:current_user.id %>
  </div>

    <div class="field">
      <%=f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_select :birthday %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_area :about %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', @profile %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Result</h1>
<br>
<% @profile.each do |profile| %>
  
<div class="well size">
 <tr>
    <td><%= image_tag profile.avatar.url, size:"30x30" %> <%= profile.firstname + " " + profile.lastname %></td>
    <td><%= link_to 'View', profile, class: "viewprofile" %></td>
</tr>
</div>

<% end %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>



  <%= image_tag @profile.avatar.url, size: "150x150" %>



<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname   if @profile.firstname.present?%>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname if @profile.lastname.present? %>
</p>

<p>
  <strong>Birthday:</strong>  

  <%= @profile.birthday.to_formatted_s(:long) if @profile.birthday.present?   %>
</p>

<p>
  <strong>About:</strong>
  <%= @profile.about  if @profile.about.present? %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender  if @profile.gender.present? %>
</p>

<p> <%= link_to current_user.friends_with?(@profile.user) || current_user.id == @profile.user_id ? " " : "Add Friend" , {:controller => 'profiles',:action => 'adduser', :id => @profile.user} %> </p>

<p><%= link_to current_user.friends_with?(@profile.user) ? " Unfriend " : " ", {:controller => 'users', :action => 'unfriend_user', :id => @profile.user} %></p>


<p>
  <% if current_user == @profile.user %>
<%= link_to 'Edit Profile', edit_profile_path(@profile) %> <br>
<%= link_to 'Change Password', {:controller => 'users', :action => 'edit'} %>
    <% end %>
<p>
  <% @profile.user.posts.order("created_at desc").each do |p| %>

      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <div class="well well-lg">
            <div class="user-name">
              <h4 align="left"> <%= image_tag @profile.avatar.url, size:"50x50" %>  <%= @profile.firstname %></h4>
            </div>
             <div class="user-post">
                <h4 align="center">  <%= p.description %></h4>
              <% if p.avatar.present? %>
                <h4 align="center"><%= image_tag p.avatar.url, size:"300x300" %></h4>
              <%else%>
                  <h4 align="center"><%#= image_tag p.avatar.url, size:"300x300" %></h4>
              <% end %>


                 <h4 align="center">Created at:  <%= time_ago_in_words(p.created_at) %></h4>
              </div>
              <hr>
            <div class="student-action" align="center">
             
               <td>
               <%= link_to 'like', {:controller => 'post', :id => p , :action =>'like'}, class: "btn btn-xs btn-danger" %>
               </td>
               <td>Likes:<%= p.votes_for.size%></td>
            </div>
          </div>
        </div>
        </div>
  <% end %>

      <%# end %>

<%#= link_to 'Edit', edit_profile_path(@profile) %> 
<%#= link_to 'Back', profiles_path %>