config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'profile/create/:id', to: 'profiles#new'
  get '/:id', to: 'posts#destroy'
  get 'commenters/create'
  get ':id/commenters', to: 'commenters#create'
  get 'users/show'
  get 'users/add_user'
  get 'profiles/add_user'
  get 'users/reject_user/:id', to: 'users#reject_user'
  get 'users/acceptuser'
  get 'users/friend'
  get 'users/profile'
  get ':controller/:action/:id'
  patch 'users/updateprofile/:id', to: 'users#updateprofile'
  put 'post/like/:id', to: 'posts#like'
  put 'post/unlike/:id', to: 'posts#unlike'
  get 'post/like/:id', to: 'posts#like'
  get 'post/unlike/:id', to: 'posts#unlike'
  get 'post/new', to: 'posts#new'
  get 'users/friend/:id', to: 'users#unfriend'



  devise_for :users

  resources :posts , :path => '/' do
     put 'like', to: 'posts#like'
     put "unlike", to: "posts#unlike"
    resources :commenters
  end
  resource :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/commenter.rb
class Commenter < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/controllers/commenters_controller.rb
class CommentersController < ApplicationController
  before_action :find_post
  before_action :find_comment, only: [:destroy, :edit, :update]
  load_and_authorize_resource :only => [:edit]


  def create
    @comment = @post.commenters.create(params[:commenter].permit(:comment))
    @comment.user_id = current_user.id
    @comment.save

    if @comment.save
      respond_to do |format|
      format.html {redirect_to posts_path}
      format.js { render :action => 'create' }
      end  

    else
        redirect_to posts_path
    end
  end

  def destroy
    @comment.destroy
    redirect_to posts_path(@post)
  end

  def edit

  end

  def update
    if @comment.update(params[:commenter].permit(:comment))
      authorize! :read, @comment
      redirect_to posts_path(@post)
    else
      render 'edit'
    end

  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = @post.commenters.find(params[:id])
  end

end

app/helpers/commenters_helper.rb
module CommentersHelper
end

app/views/commenters/_commentform.html.erb
<%=	 form_for([obj, obj.commenters.build], remote: true) do |f| %>
    <%= f.text_area :comment, id: "comment-#{obj.id}"  %><br>
    <%= f.submit " Comment" %>

<% end %>

app/views/commenters/_commentlist.html.erb
	<li class = 'comments'>
    <br><%= image_tag @comment.user.profile.avatar.url, size:"50x50" %> 
	<a href="<%= "#{profile_path(@comment.user.profile)}" %>">
    <%= @comment.user.profile.firstname + " " + @comment.user.profile.lastname %></a> : <%= @comment.comment %>
    
	<br><%=	time_ago_in_words(@comment.created_at) %> ago

	<% if current_user == @comment.user %>
            <%= link_to "Delete comment", [@comment.post, @comment], method: :delete %>
            <%= link_to "Edit comment", edit_post_commenter_path(@comment.post, @comment) %>
        <% end %>
	</li>

app/views/commenters/_newsfeedcomment.html.erb
<% obj.commenters.each do |c| %>
	<li class = 'comments'>
        <br><%= image_tag c.user.profile.avatar.url, size:"50x50" %> 
        <a href="<%= "#{profile_path(c.user.profile)}" %>"><%= c.user.profile.firstname + " " + c.user.profile.lastname %></a> : <%= c.comment %>
        <br><%=	time_ago_in_words(c.created_at) %> ago
        <% if current_user == c.user %>
            <%= link_to "Delete comment", [c.post, c], method: :delete %>
            <%= link_to "Edit comment", edit_post_commenter_path(c.post, c) %>
        <% end %>
	</li>
<% end %>
<%= render 'commenters/commentform', obj: obj %>

app/views/commenters/create.js.erb
var content = "<%= j render(:partial => 'commenters/commentlist', obj: @comment) %>";

var post = $("#post_comments_<%= @comment.post_id %>");
var last_comment = post.find('#comments > li:last');
if (last_comment.length > 0) {
	last_comment.after(content);
} else { 
	var comments = post.find('#comments');
	comments.prepend(content)			
}
$('#comment-<%= @comment.post_id %>').val("");
$('#comment-<%= @comment.post_id %>').focus();

app/views/commenters/edit.html.erb
<%=	 form_for([@post, @comment]) do |f| %>

    <%= f.text_area :comment %><br>
    <%= f.submit "Edit Comment" %>

<% end %>