config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'profile/create/:id', to: 'profiles#new'
  get '/:id', to: 'posts#destroy'
  get 'commenters/create'
  get ':id/commenters', to: 'commenters#create'
  get 'users/show'
  get 'users/add_user'
  get 'profiles/add_user'
  get 'users/reject_user/:id', to: 'users#reject_user'
  get 'users/acceptuser'
  get 'users/friend'
  get 'users/profile'
  get ':controller/:action/:id'
  patch 'users/updateprofile/:id', to: 'users#updateprofile'
  put 'post/like/:id', to: 'posts#like'
  put 'post/unlike/:id', to: 'posts#unlike'
  get 'post/like/:id', to: 'posts#like'
  get 'post/unlike/:id', to: 'posts#unlike'
  get 'post/new', to: 'posts#new'
  get 'users/friend/:id', to: 'users#unfriend'



  devise_for :users

  resources :posts , :path => '/' do
     put 'like', to: 'posts#like'
     put "unlike", to: "posts#unlike"
    resources :commenters
  end
  resource :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  #acts_as_likeable
  acts_as_votable
  belongs_to :user
  has_many :commenters, dependent: :destroy
  has_many :users, :through => :commenters
  has_attached_file :avatar
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  load_and_authorize_resource :only => [:edit]

  # GET /posts
  # GET /posts.json
  def index
    @post = Post.new
    @posts = Post.all
    @users = User.all

    @user = User.find(current_user)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

    @comments = Commenter.where(post_id: @post)
  end

  # GET /posts/new
  def new
    @post = Post.new

  end

  # GET /posts/1/edit
  def edit

  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    #@post.user_ids = current_user.id
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        authorize! :read, @post
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @user = current_user
    @post.liked_by(@user)
    redirect_to posts_path
  end

  def unlike
    @user2 = current_user
    @post.unliked_by(@user2)
    redirect_to posts_path
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :user_id, :avatar)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

    <div class="field">
      <%=f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>


    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/create.js.erb
$('#comments').append('<%= j render(:partial => commenters/newsfeedcomment, obj: post) %>');

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1 align="center">News Feed</h1>

<br>  

              <div class="inputpost">
                <div class="col-xs-8 col-xs-offset-2">
                  <div class="well well-lg">
                     
                    <%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

    <div class="field">
      <%=f.label :image %>
      <%= f.file_field :avatar %>
    </div>


    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

                  </div>
                </div>
              </div>

             <div class="row-right">
                <div class="col-xs-8 col-xs-offset-2">
                  <div class="well well-lg">
                      <h4 align="center">Friendlist</h3>
                      <%current_user.friends.each do |f| %>
                        <ul class="friendlist">
                          <%= image_tag f.profile.avatar.url, size:"50x50" %>  <%= link_to f.profile.firstname + " " + f.profile.lastname , profile_path(f.profile.id) %>
                        </ul>
                      <% end %>
                  </div>
                </div>
              </div>

          
    <%# f.posts.each do |p| %>
    <% @posts = Post.where(user_id: current_user.all_user_ids).order("created_at desc") %>
    <%@posts.each do |post| %>


        <div class="row">
          <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
             
           

              <div class="user-name">
                <h4 align="left">
                
                <a href="<%= "#{profile_path(post.user.profile)}" %>">
                  <%= image_tag post.user.profile.avatar.url, size:"50x50" %> <%= post.user.profile.firstname + " " + post.user.profile.lastname %>
                </a>
                </h4>
              
                 <h5 align="center"> <%=	post.description  %> </h5>
              <% if post.avatar.present? %>
                  <h4 align="center"><%= image_tag post.avatar.url, size:"300x300" %></h4>
              <%else%>
              <% end %>

                 <h5 align="center">Created at: <%=	time_ago_in_words(post.created_at) %> ago</h5>
          
              </div>
                  <hr>

              <div class="post-action-<%=post.id%>" align="center">
                        
                        <% if current_user.liked? post %>
                            <td>
                             <%= link_to "unLike", {:controller => 'post', :id => post , :action =>'unlike'}, class: "btn btn-danger btn-xs" %>
 
                            </td>
                        <% else %>
                            <td>
                                <%= link_to "Like", {:controller => 'post', :id => post , :action =>'like'}, class: "btn btn-danger btn-xs" %>

 
                            </td>
                        <% end %>
                        <span id="votes-count" data-id="<%= post.id %>"%>like:<%= post.get_likes.size() %></span>
                       <hr>

                    <div id="comment-action">
                      <%= link_to "View Comments", "#post_comments_#{post.id}" %>
                      
                       <section class="comments-section" id="post_comments_<%= post.id %>" >
                      <br>
                        <div id="comments">
                          <%= render 'commenters/newsfeedcomment', obj: post  %>
                        </div>
                        <% if current_user == post.user %>
                          <h6 align="right"><%= link_to 'Edit', edit_post_path(post) %></h6>
                          <h6 align="right"><%= link_to 'Delete', { :id => post ,:controller => 'posts',:action => 'destroy'} %></h6>
                        <% end %>
                      
                    </div>    
              </div>
            </div>
          </div>
        </div>

    <% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.js.erb
$('#new_post').hide().after('<%= j render("form") %>');

("#new_post").html("<%= escape_javascript(render('form', post: @post )) %>")

$("#subscribe_button").html("<%= escape_javascript(render(partial: 'subscriptions/unsubscribe', locals: { group: @group } )) %>") 

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h3 align="center"><%= @post.user.profile.firstname %></h3>
        <div class="row">
          <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
              <div class="user-post">

                <h4 align="center"><%= @post.description %></h4>
                <% if @post.avatar.present? %>
                    <h4 align="center"><%= image_tag @post.avatar.url, size:"300x300" %></h4>
                <%else%>
                    <h4 align="center"><%#= image_tag p.avatar.url, size:"300x300" %></h4>
                <% end %>
               <h4 align="center"> Created at: <%=	time_ago_in_words(@post.created_at)%></h4>
              </div>
              <hr>
              <div class="user-comment">
              </div>
            </div>
            <% if current_user == @post.user %>
            <h6 align="right"><%= link_to 'Edit', edit_post_path(@post) %></h6>
            <h6 align="right"><%= link_to 'Destroy', method: :delete, data: { confirm: 'Are you sure?' } %></h6>
                <% end %>
            <h6 align="right"> <%= link_to 'Back', posts_path %></h6>
          </div>

        </div>