config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'profile/create/:id', to: 'profiles#new'
  get '/:id', to: 'posts#destroy'
  get 'commenters/create'
  get ':id/commenters', to: 'commenters#create'
  get 'users/show'
  get 'users/add_user'
  get 'profiles/add_user'
  get 'users/reject_user/:id', to: 'users#reject_user'
  get 'users/acceptuser'
  get 'users/friend'
  get 'users/profile'
  get ':controller/:action/:id'
  patch 'users/updateprofile/:id', to: 'users#updateprofile'
  put 'post/like/:id', to: 'posts#like'
  put 'post/unlike/:id', to: 'posts#unlike'
  get 'post/like/:id', to: 'posts#like'
  get 'post/unlike/:id', to: 'posts#unlike'
  get 'post/new', to: 'posts#new'
  get 'users/friend/:id', to: 'users#unfriend'



  devise_for :users

  resources :posts , :path => '/' do
     put 'like', to: 'posts#like'
     put "unlike", to: "posts#unlike"
    resources :commenters
  end
  resource :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
    <%= devise_error_messages! %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
    <% end %>

    <div class="field">
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= f.submit "Update" %>
    </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand"> <%=link_to "Welcome #{current_user.profile.firstname }", profile_path(current_user.profile), class:"navbar-brand" %></a>
    </div>
    <ul class="nav navbar-nav">
      <li><%=	 link_to 'Home', "/" %></a></li>

      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Friend Request
        <% if current_user.requested_friends.count == 0 %>
            <%= current_user.requested_friends.count  %> 
        <% else %>
            <span class = "badge"><%= current_user.requested_friends.count  %></span>
          <% end %>

        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <nav>
            <% current_user.requested_friends.each do |f|  %>
            <li class="user"> <%= image_tag f.profile.avatar.url, size:"40x40" %> <%= link_to	f.profile.firstname + " " + f.profile.lastname, profile_path(f.profile) %></li>
            <li class="accept"><%=link_to( "Accept", {:controller => 'users', :action => 'accept_user', :id => f}, class:  "btn btn-default") %></li>
            <li class="decline"> <%=link_to( "Decline", {:controller => 'users', :action => 'reject_user', :id => f}, class: "btn btn-primary") %></li>
            <% end %>
          </nav>
        </ul>
      </li>
      <li class="search">
        <%= form_tag(profiles_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %>
          <%= submit_tag "Search" %>
        <% end %>
      </li>
      <li class="logout"><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
    </ul>
    
  </div>
</nav>

app/views/layouts/_signup.html.erb
<% resource.build_profile if resource.profile.nil? %>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>
    <%= f.fields_for :profile do |profile_fields| %>
<div class="wrap">

      <%#= f.text_field :firstname, autofocus: true, placeholder:"First Name", class:"fn" %>
      <%#= f.text_field :lastname, autofocus: true, placeholder: "Last Name", class:"ln" %>

        <div class="field">
          <%= profile_fields.text_field :firstname, placeholder:"First Name" %>


          <%= profile_fields.text_field :lastname, placeholder:"Last Name" %>

        </div>

    <div class="field">
      <%= profile_fields.number_field :mobile, placeholder:"Mobile" , class:"mob"%>

      <%#= f.number_field :mobile, autofocus: true, placeholder:"Mobile" , class:"mob"%>
    </div>

    <div class="field">
      <%= f.email_field :email, autofocus: true, placeholder:"Email Address", class:"ea" %>
    </div>

    <div class="field">
      <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %>
      <%= f.password_field :password, autocomplete: "off", placeholder:"Password", class:"pass"%>
    </div>

    <div class="field">
      <%= f.password_field :password_confirmation, autocomplete: "off", placeholder:"Confirm Password",class:"compass" %>
    </div>

    <div class="field">
      <%#= f.label :birthday %>
      <%= profile_fields.date_field :birthday, autofocus: true %>
    </div>
    <div class="field">
      <%= profile_fields.label :Gender %>
      <%= profile_fields.label :Gender_male, 'Male' %>
      <%= profile_fields.radio_button :gender, 'Male'%>
      <%= profile_fields.label :Gender_female, 'Female' %>
      <%= profile_fields.radio_button :gender, 'Female' %>
    </div>

    <div class="actions">
      <%= f.submit "Create Account" %>
    </div>
<% end %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfacebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'layouts/navbar' unless devise_controller? %>
  <%= yield %>
  </body>
</html>